# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    pull_request:
        branches: [develop, master]
    push:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install eslint
              run : |
                  yarn 

            - name: Run UT and build all
              working-directory: ./client
              run : |
                  yarn
                  yarn lint
                  yarn run test-ci
                  yarn snapshot
                  yarn build-all

    notification:
        needs: [build]
        runs-on: ubuntu-latest
        if: |
            always() && 
            (needs.build.result == 'failed' || needs.build.result == 'success')
        steps:
        - name: Send build result to slack channel
          uses: rtCamp/action-slack-notify@v2
          env: 
            SLACK_WEBHOOK: ${{ secrets.ORG_SLACK_URL }}
            SLACK_COLOR: ${{ job.status }}
            SLACK_FOOTER: Powered by CasperDash