# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install eslint
      run : |
        yarn
    
    - name: Run UT
      working-directory: ./client
      run : |
          yarn
          yarn run test-ci

    - name: Upload code coverage to codecov 
      uses: codecov/codecov-action@v2
      with:
        working-directory: './client'

    - name: Build react app
      working-directory: ./client
      run: |
        yarn
        npm run build --if-present
        aws s3 sync ./build/ s3://casperdash.io/ --delete
        aws cloudfront create-invalidation --distribution-id ${{ secrets.MAINNET_DISTRIBUTION_ID }} --paths "/*" --no-cli-pager
      env:
        CI: false 